
package client.ws.rytsa.valuaciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSValuacionesSoap", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
public interface WSValuacionesSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @param request
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.valuaciones.ArrayOfOperacionNDFAValuarData
     */
    @WebMethod(operationName = "RecuperarOperacionesNDFAValuar", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/RecuperarOperacionesNDFAValuar")
    @WebResult(name = "RecuperarOperacionesNDFAValuarResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "RecuperarOperacionesNDFAValuar", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.RecuperarOperacionesNDFAValuar")
    @ResponseWrapper(localName = "RecuperarOperacionesNDFAValuarResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.RecuperarOperacionesNDFAValuarResponse")
    public ArrayOfOperacionNDFAValuarData recuperarOperacionesNDFAValuar(
        @WebParam(name = "idSesion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        String idSesion,
        @WebParam(name = "request", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        OperacionesNDFAValuarRequestData request);

    /**
     * 
     * @param request
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.valuaciones.ArrayOfOperacionSWAPAValuarData
     */
    @WebMethod(operationName = "RecuperarOperacionesSWAPAValuar", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/RecuperarOperacionesSWAPAValuar")
    @WebResult(name = "RecuperarOperacionesSWAPAValuarResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "RecuperarOperacionesSWAPAValuar", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.RecuperarOperacionesSWAPAValuar")
    @ResponseWrapper(localName = "RecuperarOperacionesSWAPAValuarResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.RecuperarOperacionesSWAPAValuarResponse")
    public ArrayOfOperacionSWAPAValuarData recuperarOperacionesSWAPAValuar(
        @WebParam(name = "idSesion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        String idSesion,
        @WebParam(name = "request", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        OperacionesSWAPAValuarRequestData request);

    /**
     * 
     * @param fechaProceso
     * @param request
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.valuaciones.NovedadesValuacionesResponseData
     */
    @WebMethod(operationName = "InformarNovedadesValuaciones", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/InformarNovedadesValuaciones")
    @WebResult(name = "InformarNovedadesValuacionesResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "InformarNovedadesValuaciones", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.InformarNovedadesValuaciones")
    @ResponseWrapper(localName = "InformarNovedadesValuacionesResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.InformarNovedadesValuacionesResponse")
    public NovedadesValuacionesResponseData informarNovedadesValuaciones(
        @WebParam(name = "idSesion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        String idSesion,
        @WebParam(name = "request", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        ArrayOfNovedadesValuacionesRequestData request,
        @WebParam(name = "fechaProceso", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        XMLGregorianCalendar fechaProceso);

    /**
     * 
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.valuaciones.ArrayOfAgendaCuponOperacioneSWAPAValuarData
     */
    @WebMethod(operationName = "RecuperarAgendaCuponesOperacionesSWAPAValuar", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/RecuperarAgendaCuponesOperacionesSWAPAValuar")
    @WebResult(name = "RecuperarAgendaCuponesOperacionesSWAPAValuarResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "RecuperarAgendaCuponesOperacionesSWAPAValuar", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.RecuperarAgendaCuponesOperacionesSWAPAValuar")
    @ResponseWrapper(localName = "RecuperarAgendaCuponesOperacionesSWAPAValuarResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.RecuperarAgendaCuponesOperacionesSWAPAValuarResponse")
    public ArrayOfAgendaCuponOperacioneSWAPAValuarData recuperarAgendaCuponesOperacionesSWAPAValuar(
        @WebParam(name = "idSesion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        String idSesion);

    /**
     * 
     * @param fechaProceso
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.valuaciones.BEEstado
     */
    @WebMethod(operationName = "GenerarOperacionesSWAPSAValuar", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/GenerarOperacionesSWAPSAValuar")
    @WebResult(name = "GenerarOperacionesSWAPSAValuarResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "GenerarOperacionesSWAPSAValuar", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.GenerarOperacionesSWAPSAValuar")
    @ResponseWrapper(localName = "GenerarOperacionesSWAPSAValuarResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.GenerarOperacionesSWAPSAValuarResponse")
    public BEEstado generarOperacionesSWAPSAValuar(
        @WebParam(name = "idSesion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        String idSesion,
        @WebParam(name = "fechaProceso", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        XMLGregorianCalendar fechaProceso);

    /**
     * 
     * @param fechaProceso
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.valuaciones.BEEstado
     */
    @WebMethod(operationName = "GenerarOperacionesNDFAValuar", action = "http://api.patron.mae.com.ar/sistemasexternos/itau/GenerarOperacionesNDFAValuar")
    @WebResult(name = "GenerarOperacionesNDFAValuarResult", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
    @RequestWrapper(localName = "GenerarOperacionesNDFAValuar", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.GenerarOperacionesNDFAValuar")
    @ResponseWrapper(localName = "GenerarOperacionesNDFAValuarResponse", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", className = "client.ws.rytsa.valuaciones.GenerarOperacionesNDFAValuarResponse")
    public BEEstado generarOperacionesNDFAValuar(
        @WebParam(name = "idSesion", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        String idSesion,
        @WebParam(name = "fechaProceso", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau")
        XMLGregorianCalendar fechaProceso);

}
