
package client.ws.rytsa.general;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WSGeneral", targetNamespace = "http://tempuri.org/", wsdlLocation = "WSGeneral.wsdl")
public class WSGeneral
    extends Service
{

    private final static URL WSGENERAL_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/E:/DESARROLLO/jboss-4.2.3.GA/bin/WSGeneral.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSGENERAL_WSDL_LOCATION = url;
    }

    public WSGeneral(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGeneral() {
        super(WSGENERAL_WSDL_LOCATION, new QName("http://tempuri.org/", "WSGeneral"));
    }

    /**
     * 
     * @return
     *     returns WSGeneralSoap
     */
    @WebEndpoint(name = "WSGeneralSoap")
    public WSGeneralSoap getWSGeneralSoap() {
        return (WSGeneralSoap)super.getPort(new QName("http://tempuri.org/", "WSGeneralSoap"), WSGeneralSoap.class);
    }

}
