
package client.ws.rytsa.valuaciones;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WSValuaciones", targetNamespace = "http://api.patron.mae.com.ar/sistemasexternos/itau", wsdlLocation = "WSInterfaceValuaciones.wsdl")
public class WSValuaciones
    extends Service
{

    private final static URL WSVALUACIONES_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/E:/DESARROLLO/jboss-4.2.3.GA/bin/WSInterfaceValuaciones.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSVALUACIONES_WSDL_LOCATION = url;
    }

    public WSValuaciones(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSValuaciones() {
        super(WSVALUACIONES_WSDL_LOCATION, new QName("http://api.patron.mae.com.ar/sistemasexternos/itau", "WSValuaciones"));
    }

    /**
     * 
     * @return
     *     returns WSValuacionesSoap
     */
    @WebEndpoint(name = "WSValuacionesSoap")
    public WSValuacionesSoap getWSValuacionesSoap() {
        return (WSValuacionesSoap)super.getPort(new QName("http://api.patron.mae.com.ar/sistemasexternos/itau", "WSValuacionesSoap"), WSValuacionesSoap.class);
    }

}
