
package client.ws.rytsa.seguridad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSSeguridadSoap", targetNamespace = "http://tempuri.org/")
public interface WSSeguridadSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://tempuri.org/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @param idSesion
     * @param beUsuarios
     * @param createUsuariosResult
     */
    @WebMethod(operationName = "CreateUsuarios", action = "http://tempuri.org/CreateUsuarios")
    @RequestWrapper(localName = "CreateUsuarios", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.CreateUsuarios")
    @ResponseWrapper(localName = "CreateUsuariosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.CreateUsuariosResponse")
    public void createUsuarios(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beUsuarios", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<BEUsuarios> beUsuarios,
        @WebParam(name = "CreateUsuariosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> createUsuariosResult);

    /**
     * 
     * @param beNueva
     * @param beOriginal
     * @param idSesion
     * @param updateUsuariosResult
     */
    @WebMethod(operationName = "UpdateUsuarios", action = "http://tempuri.org/UpdateUsuarios")
    @RequestWrapper(localName = "UpdateUsuarios", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.UpdateUsuarios")
    @ResponseWrapper(localName = "UpdateUsuariosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.UpdateUsuariosResponse")
    public void updateUsuarios(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beOriginal", targetNamespace = "http://tempuri.org/")
        BEUsuarios beOriginal,
        @WebParam(name = "beNueva", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<BEUsuarios> beNueva,
        @WebParam(name = "UpdateUsuariosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> updateUsuariosResult);

    /**
     * 
     * @param idSesion
     * @param beUsuarios
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "DeleteUsuarios", action = "http://tempuri.org/DeleteUsuarios")
    @WebResult(name = "DeleteUsuariosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteUsuarios", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.DeleteUsuarios")
    @ResponseWrapper(localName = "DeleteUsuariosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.DeleteUsuariosResponse")
    public BEEstado deleteUsuarios(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beUsuarios", targetNamespace = "http://tempuri.org/")
        BEUsuarios beUsuarios);

    /**
     * 
     * @param idUsuario
     * @param getByIDUsuariosResult
     * @param idSesion
     * @param be
     */
    @WebMethod(operationName = "GetByIDUsuarios", action = "http://tempuri.org/GetByIDUsuarios")
    @RequestWrapper(localName = "GetByIDUsuarios", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDUsuarios")
    @ResponseWrapper(localName = "GetByIDUsuariosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDUsuariosResponse")
    public void getByIDUsuarios(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "GetByIDUsuariosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getByIDUsuariosResult,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEUsuarios> be);

    /**
     * 
     * @param getAllUsuariosResult
     * @param maxRecord
     * @param beArray
     * @param lastRecord
     * @param idSesion
     */
    @WebMethod(operationName = "GetAllUsuarios", action = "http://tempuri.org/GetAllUsuarios")
    @RequestWrapper(localName = "GetAllUsuarios", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllUsuarios")
    @ResponseWrapper(localName = "GetAllUsuariosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllUsuariosResponse")
    public void getAllUsuarios(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "GetAllUsuariosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllUsuariosResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEUsuarios> beArray);

    /**
     * 
     * @param idUsuario
     * @param bePermisos
     * @param idAccion
     * @param idSesion
     * @param getByIDPermisosResult
     */
    @WebMethod(operationName = "GetByIDPermisos", action = "http://tempuri.org/GetByIDPermisos")
    @RequestWrapper(localName = "GetByIDPermisos", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDPermisos")
    @ResponseWrapper(localName = "GetByIDPermisosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDPermisosResponse")
    public void getByIDPermisos(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "idAccion", targetNamespace = "http://tempuri.org/")
        long idAccion,
        @WebParam(name = "GetByIDPermisosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getByIDPermisosResult,
        @WebParam(name = "bePermisos", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEPermisos> bePermisos);

    /**
     * 
     * @param idAplicacion
     * @param getAllPermisosDescripResult
     * @param beArray
     * @param idSesion
     */
    @WebMethod(operationName = "GetAllPermisosDescrip", action = "http://tempuri.org/GetAllPermisosDescrip")
    @RequestWrapper(localName = "GetAllPermisosDescrip", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllPermisosDescrip")
    @ResponseWrapper(localName = "GetAllPermisosDescripResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllPermisosDescripResponse")
    public void getAllPermisosDescrip(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idAplicacion", targetNamespace = "http://tempuri.org/")
        int idAplicacion,
        @WebParam(name = "GetAllPermisosDescripResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllPermisosDescripResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEPermisos> beArray);

    /**
     * 
     * @param idAplicacion
     * @param idUsuario
     * @param beArray
     * @param idSesion
     * @param getAllPermisosResult
     */
    @WebMethod(operationName = "GetAllPermisos", action = "http://tempuri.org/GetAllPermisos")
    @RequestWrapper(localName = "GetAllPermisos", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllPermisos")
    @ResponseWrapper(localName = "GetAllPermisosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllPermisosResponse")
    public void getAllPermisos(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "idAplicacion", targetNamespace = "http://tempuri.org/")
        int idAplicacion,
        @WebParam(name = "GetAllPermisosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllPermisosResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEPermisos> beArray);

    /**
     * 
     * @param maxRecord
     * @param beArray
     * @param lastRecord
     * @param idSesion
     * @param getAllLookUpUsuariosResult
     */
    @WebMethod(operationName = "GetAllLookUpUsuarios", action = "http://tempuri.org/GetAllLookUpUsuarios")
    @RequestWrapper(localName = "GetAllLookUpUsuarios", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllLookUpUsuarios")
    @ResponseWrapper(localName = "GetAllLookUpUsuariosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllLookUpUsuariosResponse")
    public void getAllLookUpUsuarios(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "GetAllLookUpUsuariosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllLookUpUsuariosResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEUsuarios> beArray);

    /**
     * 
     * @param nuevaClaveVerificacion
     * @param idSesion
     * @param be
     * @param nuevaClave
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "ResetClave", action = "http://tempuri.org/ResetClave")
    @WebResult(name = "ResetClaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResetClave", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.ResetClave")
    @ResponseWrapper(localName = "ResetClaveResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.ResetClaveResponse")
    public BEEstado resetClave(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "nuevaClave", targetNamespace = "http://tempuri.org/")
        String nuevaClave,
        @WebParam(name = "nuevaClaveVerificacion", targetNamespace = "http://tempuri.org/")
        String nuevaClaveVerificacion,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/")
        BEUsuarios be);

    /**
     * 
     * @param getUsuarioLocalResult
     * @param beArray
     * @param idSesion
     */
    @WebMethod(operationName = "GetUsuarioLocal", action = "http://tempuri.org/GetUsuarioLocal")
    @RequestWrapper(localName = "GetUsuarioLocal", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetUsuarioLocal")
    @ResponseWrapper(localName = "GetUsuarioLocalResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetUsuarioLocalResponse")
    public void getUsuarioLocal(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "GetUsuarioLocalResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getUsuarioLocalResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEUsuarios> beArray);

    /**
     * 
     * @param puedeAprobarAutomaticamenteResult
     * @param idUsuario
     * @param valido
     * @param idAccion
     * @param idSesion
     */
    @WebMethod(operationName = "PuedeAprobarAutomaticamente", action = "http://tempuri.org/PuedeAprobarAutomaticamente")
    @RequestWrapper(localName = "PuedeAprobarAutomaticamente", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.PuedeAprobarAutomaticamente")
    @ResponseWrapper(localName = "PuedeAprobarAutomaticamenteResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.PuedeAprobarAutomaticamenteResponse")
    public void puedeAprobarAutomaticamente(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "idAccion", targetNamespace = "http://tempuri.org/")
        int idAccion,
        @WebParam(name = "PuedeAprobarAutomaticamenteResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> puedeAprobarAutomaticamenteResult,
        @WebParam(name = "valido", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> valido);

    /**
     * 
     * @param idSesionKickoff
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "KickOff", action = "http://tempuri.org/KickOff")
    @WebResult(name = "KickOffResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "KickOff", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.KickOff")
    @ResponseWrapper(localName = "KickOffResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.KickOffResponse")
    public BEEstado kickOff(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idSesionKickoff", targetNamespace = "http://tempuri.org/")
        String idSesionKickoff);

    /**
     * 
     * @param beSesiones
     * @param userName
     * @param loginSesionResult
     * @param password
     * @param ip
     */
    @WebMethod(operationName = "LoginSesion", action = "http://tempuri.org/LoginSesion")
    @RequestWrapper(localName = "LoginSesion", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.LoginSesion")
    @ResponseWrapper(localName = "LoginSesionResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.LoginSesionResponse")
    public void loginSesion(
        @WebParam(name = "Ip", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "beSesiones", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<BESesiones> beSesiones,
        @WebParam(name = "LoginSesionResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> loginSesionResult);

    /**
     * 
     * @param nuevaVerificacion
     * @param anterior
     * @param nueva
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "ChangeClave", action = "http://tempuri.org/ChangeClave")
    @WebResult(name = "ChangeClaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeClave", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.ChangeClave")
    @ResponseWrapper(localName = "ChangeClaveResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.ChangeClaveResponse")
    public BEEstado changeClave(
        @WebParam(name = "IdSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "anterior", targetNamespace = "http://tempuri.org/")
        String anterior,
        @WebParam(name = "nueva", targetNamespace = "http://tempuri.org/")
        String nueva,
        @WebParam(name = "nuevaVerificacion", targetNamespace = "http://tempuri.org/")
        String nuevaVerificacion);

    /**
     * 
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "Logout", action = "http://tempuri.org/Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.LogoutResponse")
    public BEEstado logout(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion);

    /**
     * 
     * @param idAplicacion
     * @param consultaSesionesResult
     * @param idUsuario
     * @param maxRecord
     * @param tipo
     * @param beArray
     * @param lastRecord
     * @param idSesion
     */
    @WebMethod(operationName = "ConsultaSesiones", action = "http://tempuri.org/ConsultaSesiones")
    @RequestWrapper(localName = "ConsultaSesiones", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.ConsultaSesiones")
    @ResponseWrapper(localName = "ConsultaSesionesResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.ConsultaSesionesResponse")
    public void consultaSesiones(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "idAplicacion", targetNamespace = "http://tempuri.org/")
        int idAplicacion,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        TipoSesion tipo,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "ConsultaSesionesResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> consultaSesionesResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBESesiones> beArray);

    /**
     * 
     * @param idSesion
     * @param createAccionRolResult
     * @param beAccionRol
     */
    @WebMethod(operationName = "CreateAccionRol", action = "http://tempuri.org/CreateAccionRol")
    @RequestWrapper(localName = "CreateAccionRol", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.CreateAccionRol")
    @ResponseWrapper(localName = "CreateAccionRolResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.CreateAccionRolResponse")
    public void createAccionRol(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beAccionRol", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<BEAccionRol> beAccionRol,
        @WebParam(name = "CreateAccionRolResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> createAccionRolResult);

    /**
     * 
     * @param updateAccionRolResult
     * @param beNueva
     * @param beOriginal
     * @param idSesion
     */
    @WebMethod(operationName = "UpdateAccionRol", action = "http://tempuri.org/UpdateAccionRol")
    @RequestWrapper(localName = "UpdateAccionRol", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.UpdateAccionRol")
    @ResponseWrapper(localName = "UpdateAccionRolResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.UpdateAccionRolResponse")
    public void updateAccionRol(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beOriginal", targetNamespace = "http://tempuri.org/")
        BEAccionRol beOriginal,
        @WebParam(name = "beNueva", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<BEAccionRol> beNueva,
        @WebParam(name = "UpdateAccionRolResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> updateAccionRolResult);

    /**
     * 
     * @param idSesion
     * @param beAccionRol
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "DeleteAccionRol", action = "http://tempuri.org/DeleteAccionRol")
    @WebResult(name = "DeleteAccionRolResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteAccionRol", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.DeleteAccionRol")
    @ResponseWrapper(localName = "DeleteAccionRolResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.DeleteAccionRolResponse")
    public BEEstado deleteAccionRol(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beAccionRol", targetNamespace = "http://tempuri.org/")
        BEAccionRol beAccionRol);

    /**
     * 
     * @param getByIDAccionRolResult
     * @param idSesion
     * @param idAccionRol
     * @param be
     */
    @WebMethod(operationName = "GetByIDAccionRol", action = "http://tempuri.org/GetByIDAccionRol")
    @RequestWrapper(localName = "GetByIDAccionRol", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDAccionRol")
    @ResponseWrapper(localName = "GetByIDAccionRolResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDAccionRolResponse")
    public void getByIDAccionRol(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idAccionRol", targetNamespace = "http://tempuri.org/")
        long idAccionRol,
        @WebParam(name = "GetByIDAccionRolResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getByIDAccionRolResult,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEAccionRol> be);

    /**
     * 
     * @param maxRecord
     * @param beArray
     * @param lastRecord
     * @param idSesion
     * @param getAllAccionRolResult
     */
    @WebMethod(operationName = "GetAllAccionRol", action = "http://tempuri.org/GetAllAccionRol")
    @RequestWrapper(localName = "GetAllAccionRol", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllAccionRol")
    @ResponseWrapper(localName = "GetAllAccionRolResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllAccionRolResponse")
    public void getAllAccionRol(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "GetAllAccionRolResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllAccionRolResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEAccionRol> beArray);

    /**
     * 
     * @param permisoRequerido
     * @param idAccion
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "AuthorizeAccion", action = "http://tempuri.org/AuthorizeAccion")
    @WebResult(name = "AuthorizeAccionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AuthorizeAccion", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.AuthorizeAccion")
    @ResponseWrapper(localName = "AuthorizeAccionResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.AuthorizeAccionResponse")
    public BEEstado authorizeAccion(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "idAccion", targetNamespace = "http://tempuri.org/")
        long idAccion,
        @WebParam(name = "permisoRequerido", targetNamespace = "http://tempuri.org/")
        TipoPermiso permisoRequerido);

    /**
     * 
     * @param maxRecord
     * @param getAllAccionesResult
     * @param tipo
     * @param beArray
     * @param lastRecord
     * @param idSesion
     */
    @WebMethod(operationName = "GetAllAcciones", action = "http://tempuri.org/GetAllAcciones")
    @RequestWrapper(localName = "GetAllAcciones", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllAcciones")
    @ResponseWrapper(localName = "GetAllAccionesResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllAccionesResponse")
    public void getAllAcciones(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        TipoAccion tipo,
        @WebParam(name = "GetAllAccionesResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllAccionesResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEAcciones> beArray);

    /**
     * 
     * @param setConfiguracionseguridadResult
     * @param idSesion
     * @param be
     */
    @WebMethod(operationName = "SetConfiguracionseguridad", action = "http://tempuri.org/SetConfiguracionseguridad")
    @RequestWrapper(localName = "SetConfiguracionseguridad", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.SetConfiguracionseguridad")
    @ResponseWrapper(localName = "SetConfiguracionseguridadResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.SetConfiguracionseguridadResponse")
    public void setConfiguracionseguridad(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<BEConfiguracionseguridad> be,
        @WebParam(name = "SetConfiguracionseguridadResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> setConfiguracionseguridadResult);

    /**
     * 
     * @param getConfiguracionseguridadResult
     * @param be
     */
    @WebMethod(operationName = "GetConfiguracionseguridad", action = "http://tempuri.org/GetConfiguracionseguridad")
    @RequestWrapper(localName = "GetConfiguracionseguridad", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetConfiguracionseguridad")
    @ResponseWrapper(localName = "GetConfiguracionseguridadResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetConfiguracionseguridadResponse")
    public void getConfiguracionseguridad(
        @WebParam(name = "GetConfiguracionseguridadResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getConfiguracionseguridadResult,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEConfiguracionseguridad> be);

    /**
     * 
     * @param maxRecord
     * @param beArray
     * @param lastRecord
     * @param idSesion
     * @param getAllAplicacionesResult
     */
    @WebMethod(operationName = "GetAllAplicaciones", action = "http://tempuri.org/GetAllAplicaciones")
    @RequestWrapper(localName = "GetAllAplicaciones", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllAplicaciones")
    @ResponseWrapper(localName = "GetAllAplicacionesResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllAplicacionesResponse")
    public void getAllAplicaciones(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "GetAllAplicacionesResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllAplicacionesResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBEAplicaciones> beArray);

    /**
     * 
     * @param totalrecord
     * @param maxRecord
     * @param fechaIni
     * @param fechaFin
     * @param ip
     * @param idAplicacion
     * @param codigo
     * @param considerarHoras
     * @param categoria
     * @param idUsuario
     * @param getAllLogResult
     * @param tipo
     * @param beArray
     * @param idSesion
     * @param lastRecord
     */
    @WebMethod(operationName = "GetAllLog", action = "http://tempuri.org/GetAllLog")
    @RequestWrapper(localName = "GetAllLog", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllLog")
    @ResponseWrapper(localName = "GetAllLogResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllLogResponse")
    public void getAllLog(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "IdAplicacion", targetNamespace = "http://tempuri.org/")
        int idAplicacion,
        @WebParam(name = "IdUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "Tipo", targetNamespace = "http://tempuri.org/")
        int tipo,
        @WebParam(name = "Categoria", targetNamespace = "http://tempuri.org/")
        String categoria,
        @WebParam(name = "Fecha_Ini", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fechaIni,
        @WebParam(name = "Fecha_Fin", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fechaFin,
        @WebParam(name = "Ip", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "Codigo", targetNamespace = "http://tempuri.org/")
        String codigo,
        @WebParam(name = "ConsiderarHoras", targetNamespace = "http://tempuri.org/")
        short considerarHoras,
        @WebParam(name = "GetAllLogResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllLogResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBELog> beArray,
        @WebParam(name = "totalrecord", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> totalrecord);

    /**
     * 
     * @param totalrecord
     * @param maxRecord
     * @param fechaIni
     * @param fechaFin
     * @param ip
     * @param idAplicacion
     * @param codigo
     * @param considerarHoras
     * @param categoria
     * @param idUsuario
     * @param tipo
     * @param beArray
     * @param idSesion
     * @param lastRecord
     * @param getAllLogTestigosResult
     */
    @WebMethod(operationName = "GetAllLogTestigos", action = "http://tempuri.org/GetAllLogTestigos")
    @RequestWrapper(localName = "GetAllLogTestigos", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllLogTestigos")
    @ResponseWrapper(localName = "GetAllLogTestigosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetAllLogTestigosResponse")
    public void getAllLogTestigos(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "lastRecord", targetNamespace = "http://tempuri.org/")
        long lastRecord,
        @WebParam(name = "maxRecord", targetNamespace = "http://tempuri.org/")
        long maxRecord,
        @WebParam(name = "IdAplicacion", targetNamespace = "http://tempuri.org/")
        int idAplicacion,
        @WebParam(name = "IdUsuario", targetNamespace = "http://tempuri.org/")
        long idUsuario,
        @WebParam(name = "Tipo", targetNamespace = "http://tempuri.org/")
        int tipo,
        @WebParam(name = "Categoria", targetNamespace = "http://tempuri.org/")
        String categoria,
        @WebParam(name = "Fecha_Ini", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fechaIni,
        @WebParam(name = "Fecha_Fin", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fechaFin,
        @WebParam(name = "Ip", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "Codigo", targetNamespace = "http://tempuri.org/")
        String codigo,
        @WebParam(name = "ConsiderarHoras", targetNamespace = "http://tempuri.org/")
        short considerarHoras,
        @WebParam(name = "GetAllLogTestigosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getAllLogTestigosResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBELog> beArray,
        @WebParam(name = "totalrecord", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> totalrecord);

    /**
     * 
     * @param id
     * @param getByIDLogTestigosResult
     * @param idSesion
     * @param be
     */
    @WebMethod(operationName = "GetByIDLogTestigos", action = "http://tempuri.org/GetByIDLogTestigos")
    @RequestWrapper(localName = "GetByIDLogTestigos", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDLogTestigos")
    @ResponseWrapper(localName = "GetByIDLogTestigosResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDLogTestigosResponse")
    public void getByIDLogTestigos(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        long id,
        @WebParam(name = "GetByIDLogTestigosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getByIDLogTestigosResult,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BELog> be);

    /**
     * 
     * @param id
     * @param getByIDLogResult
     * @param idSesion
     * @param be
     */
    @WebMethod(operationName = "GetByIDLog", action = "http://tempuri.org/GetByIDLog")
    @RequestWrapper(localName = "GetByIDLog", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDLog")
    @ResponseWrapper(localName = "GetByIDLogResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetByIDLogResponse")
    public void getByIDLog(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        long id,
        @WebParam(name = "GetByIDLogResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getByIDLogResult,
        @WebParam(name = "be", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BELog> be);

    /**
     * 
     * @param getUltimosAccesosAlSistemaResult
     * @param beArray
     * @param idSesion
     */
    @WebMethod(operationName = "GetUltimosAccesosAlSistema", action = "http://tempuri.org/GetUltimosAccesosAlSistema")
    @RequestWrapper(localName = "GetUltimosAccesosAlSistema", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetUltimosAccesosAlSistema")
    @ResponseWrapper(localName = "GetUltimosAccesosAlSistemaResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetUltimosAccesosAlSistemaResponse")
    public void getUltimosAccesosAlSistema(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "GetUltimosAccesosAlSistemaResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<BEEstado> getUltimosAccesosAlSistemaResult,
        @WebParam(name = "beArray", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfBELog> beArray);

    /**
     * 
     * @param beLog
     * @param idSesion
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "EnviarBELog", action = "http://tempuri.org/EnviarBELog")
    @WebResult(name = "EnviarBELogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviarBELog", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.EnviarBELog")
    @ResponseWrapper(localName = "EnviarBELogResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.EnviarBELogResponse")
    public BEEstado enviarBELog(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "beLog", targetNamespace = "http://tempuri.org/")
        BELog beLog);

    /**
     * 
     * @param codigo
     * @param categoria
     * @param aplicacion
     * @param fecha
     * @param tipo
     * @param descripcion
     * @param idSesion
     * @param tipoDescripcion
     * @param ip
     * @param origen
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "Enviar", action = "http://tempuri.org/Enviar")
    @WebResult(name = "EnviarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Enviar", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.Enviar")
    @ResponseWrapper(localName = "EnviarResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.EnviarResponse")
    public BEEstado enviar(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "aplicacion", targetNamespace = "http://tempuri.org/")
        int aplicacion,
        @WebParam(name = "codigo", targetNamespace = "http://tempuri.org/")
        String codigo,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        TipoLog tipo,
        @WebParam(name = "categoria", targetNamespace = "http://tempuri.org/")
        String categoria,
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha,
        @WebParam(name = "origen", targetNamespace = "http://tempuri.org/")
        String origen,
        @WebParam(name = "ip", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "tipoDescripcion", targetNamespace = "http://tempuri.org/")
        TipoDescripcion tipoDescripcion,
        @WebParam(name = "descripcion", targetNamespace = "http://tempuri.org/")
        String descripcion);

    /**
     * 
     * @param codigo
     * @param categoria
     * @param aplicacion
     * @param fecha
     * @param tipo
     * @param descripcion
     * @param idSesion
     * @param tipoDescripcion
     * @param ip
     * @param origen
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "EnviarLog", action = "http://tempuri.org/EnviarLog")
    @WebResult(name = "EnviarLogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviarLog", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.EnviarLog")
    @ResponseWrapper(localName = "EnviarLogResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.EnviarLogResponse")
    public BEEstado enviarLog(
        @WebParam(name = "idSesion", targetNamespace = "http://tempuri.org/")
        String idSesion,
        @WebParam(name = "aplicacion", targetNamespace = "http://tempuri.org/")
        int aplicacion,
        @WebParam(name = "codigo", targetNamespace = "http://tempuri.org/")
        String codigo,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        TipoLog tipo,
        @WebParam(name = "categoria", targetNamespace = "http://tempuri.org/")
        String categoria,
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha,
        @WebParam(name = "origen", targetNamespace = "http://tempuri.org/")
        String origen,
        @WebParam(name = "ip", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "tipoDescripcion", targetNamespace = "http://tempuri.org/")
        TipoDescripcion tipoDescripcion,
        @WebParam(name = "descripcion", targetNamespace = "http://tempuri.org/")
        String descripcion);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDACConfiguraciones", action = "http://tempuri.org/GetDACConfiguraciones")
    @WebResult(name = "GetDACConfiguracionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDACConfiguraciones", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetDACConfiguraciones")
    @ResponseWrapper(localName = "GetDACConfiguracionesResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.GetDACConfiguracionesResponse")
    public String getDACConfiguraciones();

    /**
     * 
     * @param versionCliente
     * @param idaplicacion
     * @return
     *     returns client.ws.rytsa.seguridad.BEEstado
     */
    @WebMethod(operationName = "CheckCompatibilidadVersionCliente", action = "http://tempuri.org/CheckCompatibilidadVersionCliente")
    @WebResult(name = "CheckCompatibilidadVersionClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckCompatibilidadVersionCliente", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.CheckCompatibilidadVersionCliente")
    @ResponseWrapper(localName = "CheckCompatibilidadVersionClienteResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.CheckCompatibilidadVersionClienteResponse")
    public BEEstado checkCompatibilidadVersionCliente(
        @WebParam(name = "Idaplicacion", targetNamespace = "http://tempuri.org/")
        long idaplicacion,
        @WebParam(name = "VersionCliente", targetNamespace = "http://tempuri.org/")
        String versionCliente);

    /**
     * 
     * @param userName
     * @param password
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LogTest", action = "http://tempuri.org/LogTest")
    @WebResult(name = "LogTestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LogTest", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.LogTest")
    @ResponseWrapper(localName = "LogTestResponse", targetNamespace = "http://tempuri.org/", className = "client.ws.rytsa.seguridad.LogTestResponse")
    public String logTest(
        @WebParam(name = "Ip", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

}
